- azooKeyMac/InputController/Actions/UserAction.swift
- azooKeyMac/InputController/InputMode.swift
- azooKeyMac/InputController/InputState.swift
Resolve #18 
実装上の困難はないが、カーソル移動（ctrl+F/B）などは現在未サポートのため追加しなかった。
> feat: Ctrl+Hでbackspaceする機能を追加

- azooKeyMac.xcodeproj/project.pbxproj
- azooKeyMac/InputController/azooKeyMacInputController.swift
> [feat] Zenzai利用時に学習機能を有効化

- azooKeyMac.xcodeproj/project.pbxproj
以下を取り込み
* https://github.com/ensan-hcl/AzooKeyKanaKanjiConverter/pull/111
> feat: 学習を弱化

- azooKeyMac/Windows/ConfigWindow.swift
Appleの推奨するデザインで設定画面を調整し、固有名詞などにはヘルプボタンを追加した。
> feat:  変換ウィンドウをかっこよくした

- azooKeyMac/Configs/BoolConfigItem.swift
- azooKeyMac/InputController/InputMode.swift
- azooKeyMac/Windows/ConfigWindow.swift
> 「、」「。」の代わりに「,」「.」を入力する設定を追加

- README.md
Discordでアドバイスされた件です。install.sh にいれるほどではなくREADMEで触れるだけでよいかなと。
> [doc] readme: mention to git submodules

- azooKeyMac/InputController/SegmentsManager.swift
- azooKeyMac/InputController/azooKeyMacInputController.swift
* この実装自体だと大したうまみはない
* 今後、ライブ変換のON/OFFで変換ウィンドウの出し方を変える予定である
* その際、SegmentsManagerがここを持っていた方が何かと都合が良くなる
> refactor: 変換候補ウィンドウを出す/出さないの調整をSegmentsManagerサイドで管理するように変更

- azooKeyMac/InputController/CandidateView.swift
- azooKeyMac/InputController/SegmentsManager.swift
- azooKeyMac/InputController/azooKeyMacInputController.swift
* TODO
https://github.com/user-attachments/assets/3e5896d3-f886-457b-a450-7e48badbd61e
> feat: ライブ変換を利用しない場合に変換候補ウィンドウが自動で表示される機能を追加

- azooKeyMac/InputController/CandidateView.swift
> feat: 変換候補ウィンドウのデザインを丸みを帯びたものに変更

- azooKeyMac/InputController/CandidateView.swift
> feat: 変換候補ウィンドウの数字の高さを微調整

- azooKeyMac/Configs/BoolConfigItem.swift
- azooKeyMac/InputController/Actions/ClientAction.swift
- azooKeyMac/InputController/InputState.swift
- azooKeyMac/InputController/SegmentsManager.swift
- azooKeyMac/InputController/azooKeyMacInputController.swift
- azooKeyMac/InputController/azooKeyMacInputControllerHelper.swift
- azooKeyMac/Windows/ConfigWindow.swift
* configから明示的に有効化しない限り無効になっているので誤爆しない
* dを押してデバッグモード、Dを押して解除
> feat: デバッグウィンドウ機能を追加

- azooKeyMac/InputController/Actions/ClientAction.swift
- azooKeyMac/InputController/InputState.swift
- azooKeyMac/InputController/azooKeyMacInputController.swift
> feat: 全角スペースをデフォルトに変更

- azooKeyMac/InputController/azooKeyMacInputController.swift
> case .removeLastMarkedText:でselectionIndexをリセットするように修正

- README.md
> docs: README.mdを更新

- azooKeyMac/InputController/CandidateWindow/BaseCandidateViewController.swift
- azooKeyMac/InputController/CandidateWindow/CandidateView.swift
- azooKeyMac/InputController/CandidateWindow/SuggestCandidatesViewController.swift
> refactor: BaseCandidateViewControllerに処理を共通化

- azooKeyMac/InputController/InputMode.swift
> fix: ＜＞の入力ができない問題を修正

- azooKeyMac/Configs/BoolConfigItem.swift
- azooKeyMac/Windows/ConfigWindow.swift
> fix: 利用されていなかった「より多様な候補を提案」の設定を削除

- azooKeyMac.xcodeproj/project.pbxproj
以下のPRを反映
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/161
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/159
> chore: AzooKeyKanaKanjiConverterのバージョンを更新

- azooKeyMac/InputController/CandidateWindow/CandidateView.swift
- azooKeyMac/InputController/azooKeyMacInputController.swift
候補ウインドウが表示された状態で、数字キーを入力したときに
数字に該当する文字が入力されない不具合を修正。
> Fix: 数字キーによる選択時の不具合を修正

- .gitignore
- Core/Package.swift
- Core/Sources/Core/Metadata/Git.swift
- Core/Sources/Metadata/git.c
- Core/Sources/Metadata/git.h
- Core/Sources/Metadata/include/git.h
- Core/Tests/CoreTests/MetadataTests/MetadataTests.swift
- azooKeyMac/InputController/SegmentsManager.swift
- azooKeyMac/Windows/ConfigWindow.swift
* ただし、キャッシュの関係で更新されないことがあるっぽい。これは要注意かも。
> feat: バージョン情報を自動取得・表示できるよう修正

- Core/Package.swift
> feat: update package version

- Core/Package.swift
resolve #140 
以下のPRなどの変更を反映
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/199
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/197
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/196
> fix: fix learning-related bugs by updating AZKKC

- README.md
> README.md に開発開始時の tips を追加

- Core/Sources/Core/Metadata/Version.swift
- Core/Tests/CoreTests/MetadataTests/VersionTests.swift
- azooKeyMac/InputController/UpdateChecker.swift
- azooKeyMac/InputController/azooKeyMacInputController.swift
- azooKeyMac/InputController/azooKeyMacInputControllerHelper.swift
* 1日に1回アップデートをチェックし、もしもアップデートがあればazooKeyのメニュー上に表示
* クリックするとGitHubのサイトが開く
> feat: アップデートがある場合、メニューバー上にアップデートの存在を知らせるメニューを追加

- install.sh
ビルドの成功を確認するため、`--dry-run`オプションを追加
> feat: add --dry-run option

- Core/Package.swift
以下の修正が取り込まれる予定。
バグ修正
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/205
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/212
高速化
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/208
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/209
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/213
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/214
> feat: 変換エンジンを更新

- azooKeyMac/InputController/UserAction+getUserAction.swift
fix: #185 
たぶんこれで期待される動作になっていると思うが、実機がないので未検証。リリース後に再調整の余地あり。
> fix: テンキーで'/', '.', ','が正しく動作しない問題を修正し、エンターキーの問題も修正
