azooKey/azooKey-Desktop

azooKeyMac/azooKeyMacInputController.swift
#7 において`¥`/`\`キーの挙動を実装した際、`|`を考慮していなかった。この修正ではシフトの状態を考慮することによってこの問題を修正する。
=> fix: `|`が入力不可能になっていた問題を修正

azooKeyMac/azooKeyMacInputController.swift
ライブ変換中、1文字のみの入力でもライブ変換が適用され、使いづらい問題があった。この修正ではライブ変換の適用を2文字以上に限定することでこの問題を解決する。
=> fix: 1文字のみ入力されている状態の場合、ライブ変換を適用しない

azooKeyMac/InputController/Actions/ClientAction.swift, azooKeyMac/InputController/Actions/UserAction.swift, azooKeyMac/InputController/InputMode.swift, azooKeyMac/InputController/InputState.swift, azooKeyMac/InputController/azooKeyMacInputController.swift
現在のazooKey on macOSでは入力中にEscapeを押した場合の挙動が入力のリセットではなく「見た目上消える」というものになっていたので、明示的にハンドリング処理を書いて解決した。
=> fix: escapeを押した場合の挙動を修正

azooKeyMac/InputController/azooKeyMacInputController.swift
`handleDirectInputMode`関数を #11 でリファクタリングしたタイミングで、本来関数自体から脱出すべきとこで脱出できないケースが発生していた。このPRではこの問題を修正する。
fix #24
=> fix: 英語入力が日本語入力になってしまう問題を修正

.gitmodules, azooKeyMac.xcodeproj/project.pbxproj, azooKeyMac/Configs/ConfigItem.swift, azooKeyMac/Configs/StringConfigItem.swift, azooKeyMac/InputController/azooKeyMacInputController.swift, azooKeyMac/Windows/ConfigWindow.swift
* AzooKeyKanaKanjiConverterのコミットを更新し、文脈・プロフィールAPIを利用可能にした
* プロンプト付き変換の一環として、プロフィールを設定できるようにした
* 同じ行のテキストを文脈として変換器に与えることで、確定済みのテキストに合わせた精度の高い変換を実現した
* モデルウェイトを更新した。zenz-v2のウェイトはzenz-v1よりも30MB小さい
=> feat: zenz-v2を用いたZenzaiに更新する

azooKeyMac/InputController/InputState.swift
macOSの標準の入力では「shift+space」を入力すると1つ上の候補を選択できる。独自ウィンドウの機能を追加したのでこの機能を追加した。
=> feat: shift+spaceで1つ上の候補を選択する機能を追加

azooKeyMac/InputController/CandidateView.swift
* 次のようなバグがあった
1. IMを複数個登録
2. azooKeyから別のIMを経由して一巡させる
3. 再度azooKeyを起動
4. ウィンドウが出てこなくなる
* 昨日（3da0dd）の時点では発生していないバグだったので、ここから現時点までで二分探索した結果`9e772fca7cd74e2619e11aa9620baaafb38d6cc9`が該当コミットとわかった
* デバッグを行ったところ、windowのnewFrameのwidthに400より小さい値を設定すると発生することがわかった。
* おそらくウィンドウの初期化直後に400でsetFrameしていることと関係がありそうだが、詳細は不明
=> fix: 変換ウィンドウが消えるバグを修正

azooKeyMac.xcodeproj/project.pbxproj, azooKeyMac/Configs/BoolConfigItem.swift, azooKeyMac/InputController/Actions/ClientAction.swift, azooKeyMac/InputController/InputState.swift, azooKeyMac/InputController/azooKeyMacInputController.swift, azooKeyMac/Windows/ConfigWindow.swift
以下のPRで実装した新モードを適用した。このモードは変換ボタンを押して候補リストを表示する場合にのみ有効になり、これまでより若干長い時間を必要とするものの、かなりリッチな変換候補を表示してくれる。
* https://github.com/ensan-hcl/AzooKeyKanaKanjiConverter/pull/118
* Before
* After
=> feat: リッチなN-Best解の表示を実現

azooKeyMac.xcodeproj/project.pbxproj, azooKeyMac/InputController/Actions/UserAction.swift, azooKeyMac/InputController/CandidateView.swift, azooKeyMac/InputController/InputState.swift, azooKeyMac/InputController/SegmentsManager.swift, azooKeyMac/InputController/azooKeyMacInputController.swift, azooKeyMac/InputController/azooKeyMacInputControllerHelper.swift
これまで、入力状態の管理はazooKeyInputControllerで引き受けていたが
azooKeyInputControllerは様々なタスクを持ったクラスであり、やや複雑化していた。そこで役割の一部をSegmentsControllerとして新たに分割し、ここでComposingTextやMarkedText、Candidatesを管理することにした。
=> refactor: SegmentsManagerクラスを導入し、MarkedTextの管理や変換候補の管理をここに統一した

azooKeyMac.xcodeproj/project.pbxproj, azooKeyMac/InputController/Actions/ClientAction.swift, azooKeyMac/InputController/InputState.swift, azooKeyMac/InputController/SegmentsManager.swift, azooKeyMac/InputController/azooKeyMacInputController.swift
これまでazooKey on macOSではスマホ版の挙動に倣い、第一候補として入力全体を変換した候補を表示していた。しかし、デスクトップ環境のIMEで標準的な挙動は第一候補として単文節の変換を出すものである。そこで、これに倣って単文節の変換候補を優先的に表示し、そのあとで全体の変換を差し込むように修正した
=> feat: 単文節の変換を優先的に表示し、そのあとで入力全体の変換候補を出すように変更

azooKeyMac/InputController/Actions/ClientAction.swift, azooKeyMac/InputController/CandidateView.swift, azooKeyMac/InputController/InputState.swift, azooKeyMac/InputController/SegmentsManager.swift, azooKeyMac/InputController/azooKeyMacInputController.swift
ライブ変換のない一般的なIMEでは、入力して（composing）スペースを押すと「最も優れた変換候補がプレビューされる」という挙動（previewing）が発生し、もう一度スペースを押して初めて変換候補の一覧が出てくる（selecting）。一方、現在のazooKey on macOSの実装はそうなっておらず、composingからいきなりselectingに遷移している。
そこで、ライブ変換がオフになっている場合、composingから1度目のスペースでpreviewingに遷移し、次にselectingに遷移するように変更した。このpreviwingの状態はこの後候補を確定するたびに戻ってくるものである。
このpreviewingを追加したことにより、出来上がった候補を一度確認してからEnterを押して確定する通常の利用フローがそのまま使えるようになり、azooKeyを利用する際の体験が大きく向上した。
なお、この機能の実現のため、いくつかの追加リファクタリングを入れた。
* `SegmentsManager`の側で候補の選択状態までを担うように変更した。これによって`SegmentsManager`が候補ウィンドウに関するほとんどを管理できるようになる。
* `InputState`における`event`関数をimmutableにした。これまでこの関数は自身を変更する`mutating`メソッドだったが、本来的に処理の結果がわからないと遷移が定まらないケースがあるため、やや苦しい実装を招いていた。immutableにして、遷移をコールバックの形で返す実装としたことによって、処理がシンプルに書けるようになり、扱いやすくなったと思われる。
* `ClientAction`として`sequence`を廃止した。`sequence`はケースを増やさずに合成的な動作を実現する …
=> feat: 「プレビュー」の状態を追加し、composingとselectingの間でここに遷移するように変更

pkgbuild.sh
Resolve #61 
以下のリリースに署名付きのバージョンを追加した。
https://github.com/ensan-hcl/azooKey-Desktop/releases/tag/v0.1.0-alpha.9
=> feat: notarizationをpkgbuildのプロセスに追加

azooKeyMac.xcodeproj/project.pbxproj
前回のバージョンからの変更として
* タイポ訂正が削除
* 「xn→ん」などのローマ字かなテーブルの修正
* プロフィール付き変換の性能改善
* 濁点つき仮名が変換に混じる問題を修正
=> chore: zenzaiバージョンを更新

azooKeyMac/InputController/Actions/UserAction.swift, azooKeyMac/InputController/InputMode.swift, azooKeyMac/InputController/InputState.swift
実装
```
変換の選択
ctrl + p : 上
ctrl + n : 下
変換区切りの変更
ctrl + i : 区切りを左に
ctrl + o : 区切りを右に
ctrl + f : 変換の選択を右に
ctrl + b : 変換の選択を左に
かな英字変換
ctrl + j : ひらがな
ctrl + k : カタカナ
```
現状のFnキーでの変換でも対応していないので、優先度が低いと判断して未実装
```
ctrl + l : 全角英字 ｚｅｎｋａｋｕｅｉｊｉ
ctrl + ; : 半角英字 hankakueiji
```
=> 27 feature macのショートカットキーに対応

install.sh
`install.sh` で以下の2点を変更しております。
1. `.xcworkspace` を `.xcodeproj` に変更
`.xcworkspace` が指定されていたのですがGitになかったことと、 `.xcodeproj` でもビルドが通るようでしたので変更してみました。
2. インストール先をグローバルではなく、ユーザ毎の `~/Library/Input Methods` に変更
ちょっと検証不足な面もあるのですが、自分の環境（macOS Sonoma 14.3.1）ではグローバルインストールでは環境設定に出てきませんでした（再起動など必要でしょうか？）。
ローカルですと無事に出てきましたので変更してみました。
なお、この場合は手元でazookeyのバイナリを別途実行しておかないと作動しませんでした。グローバルの場合は自動的に立ち上がる形でしょうか？
また、他の人の開発にも影響するかと思いますので、指示していただいたらコミットを外します（別コミットにしております。
いずれも何か見落としなどあるかと思いますので、ぜひご指摘ください。
よろしくお願いいたします。
=> chore: install.shでxcodeprojファイルを利用するよう変更

azooKeyMac.xcodeproj/project.pbxproj, azooKeyMac/AppDelegate.swift, azooKeyMac/Configs/CustomCodableConfigItem.swift, azooKeyMac/InputController/SegmentsManager.swift, azooKeyMac/Windows/ConfigWindow.swift, azooKeyMac/Windows/UserDictionaryEditorWindow.swift
* ユーザ辞書の簡易的な設定画面を追加
* ユーザ辞書を変換に反映するように設定
=> feat: ユーザ辞書機能を実装

azooKeyMac/InputController/CandidateView.swift
候補リストのデフォルト幅が少し狭いようだったので広くしました。
macOSの設定次第の可能性もありますので、指摘ください。
（なお、Discordのスクリーンショットでは同様に[狭くなっている方もいる](https://discord.com/channels/1166734354492440638/1219932948799946792/1289491409702879242) ようです）
=> 番号付きの候補リスト幅を少し広くする

azooKeyMac.xcodeproj/project.pbxproj, azooKeyMac/Configs/StringConfigItem.swift, azooKeyMac/Extensions/KeychainHelper.swift, azooKeyMac/Windows/ConfigWindow.swift
- OpenAI APIキーの保存をUserDefaultsからKeychainに変更
- ConfigのAPIキーの入力フィールドをSecureFieldに変更
=> security: OpenAI APIキーをkeychainに保存するように変更

azooKeyMac.xcodeproj/project.pbxproj, azooKeyMac/InputController/SegmentsManager.swift
以下を含むバージョンを取り込んで、挙動を修正
* https://github.com/ensan-hcl/AzooKeyKanaKanjiConverter/pull/136
* https://github.com/ensan-hcl/AzooKeyKanaKanjiConverter/pull/139
そのほか、以下の変更も含まれる。
* https://github.com/ensan-hcl/AzooKeyKanaKanjiConverter/pull/134
* https://github.com/ensan-hcl/AzooKeyKanaKanjiConverter/pull/137
=> fix: Zenzaiがなくてもユーザ辞書が動作するように修正

azooKeyMac.xcodeproj/project.pbxproj
Xcode 16の新機能である「フォルダ」を使うと、フォルダ配下のファイルが全て自動的にXcodeに認識されるようになる。この挙動のおかげで、ファイルの追加や削除を行った際のxcodeprojファイルの差分を大きく減らすことができて、コンフリクト解消などの手間が生じづらくなることを期待できる。
=> refactor: use folders instead of groups

azooKeyMac/InputController/CandidateView.swift
マージでミスがあったので修正
https://github.com/ensan-hcl/azooKey-Desktop/pull/78#discussion_r1789057098
=> fix: #76 を復活させる

azooKeyMac/InputController/Actions/UserAction.swift, azooKeyMac/InputController/InputMode.swift, azooKeyMac/InputController/InputState.swift, azooKeyMac/InputController/azooKeyMacInputController.swift
- Suggestのショートカットを既存のキーバインドと競合しないctrl + sに変更
- 補完機能がオフのときにショートカットの入力をfallthroughする
=> fix: Suggestのショートカットを既存のキーバインドと競合しないctrl + sに変更

azooKeyMac/Configs/BoolConfigItem.swift
Fixes #94
Update the default value of the DebugWindow setting to false.
* Change the `default` value of the `DebugWindow` struct in `azooKeyMac/Configs/BoolConfigItem.swift` from `true` to `false`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/ensan-hcl/azooKey-Desktop/pull/95?shareId=84afc338-f5f9-4945-b420-07bd485024ef).
=> Fix: デバッグウィンドウの表示設定をデフォルトでオフにする

azooKeyMac/InputController/SegmentsManager.swift, azooKeyMac/InputController/azooKeyMacInputController.swift
#97 を修正
* getLeftSideContextの実行タイミングに依存しそうで嫌だったので、**getLeftSideContextを常にinsertの前に呼ぶ**ことで、**leftSideContextに確定された部分が含まれないこと**を保証した
=> fix: force left side context to be up-to-date

azooKeyMac/InputController/Actions/ClientAction.swift, azooKeyMac/InputController/InputLanguage.swift, azooKeyMac/InputController/InputMode.swift, azooKeyMac/InputController/InputState.swift, azooKeyMac/InputController/SegmentsManager.swift, azooKeyMac/InputController/UserAction+getUserAction.swift, azooKeyMac/InputController/azooKeyMacInputController.swift
Resolve #111 
* direct modeを廃止
* input languageの概念を導入
=> feat: 英語でも予測入力の候補を利用可能に

azooKeyMac/Configs/BoolConfigItem.swift, azooKeyMac/InputController/SegmentsManager.swift, azooKeyMac/InputController/azooKeyMacInputController.swift, azooKeyMac/InputController/azooKeyMacInputControllerHelper.swift, azooKeyMac/Windows/ConfigWindow.swift
Fixes #112
Remove the 英単語変換 (English Conversion) feature and set the default behavior to false.
* **azooKeyMac/Configs/BoolConfigItem.swift**
- Remove the `EnglishConversion` struct.
* **azooKeyMac/InputController/azooKeyMacInputController.swift**
- Remove the `englishConversionEnabled` property.
- Remove the `englishConversionToggleMenuItem` property.
- Remove the `updateEnglishConversionToggleMenuItem` method.
- Remove the `toggleEnglishConversion` method.
- Remove the `updateEnglishConversionToggleMenuItem` call in `activateServer` method.
* **azooKeyMac/Windows/ConfigWindow.swift**
- Remove the toggle for enabling English conversion.
* **azooKeyMac/InputController/azooKeyMacInputControllerHelper.swift**
- Remove the `englishConversionToggleMenuItem` property.
- Remove the …
=> feat: Remove English conversion feature

Core/.gitignore, Core/Package.swift, Core/Sources/Core/Core.swift, Core/Tests/CoreTests/CoreTests.swift, azooKeyMac.xcodeproj/project.pbxproj
* AzooKeyKanaKanjiConverterのバージョンをv0.8.0に更新
* Swift 6.1で導入されたSwift Package Traitsを利用できるよう、Swift PackageをXcodeproj内に追加
* 以降はこのSwift Package内にロジック・テストを移動する
=> refactor: update AZKKC to v0.8.0 and support Zenzai trait

.github/workflows/swift.yml, azooKeyMac.xcodeproj/project.pbxproj, azooKeyMac/Extensions/KeychainHelper.swift, azooKeyMac/InputController/OpenAIClient.swift
This pull request introduces a GitHub Actions workflow for Swift development, updates build settings in the Xcode project, and improves string decoding in the codebase. These changes enhance CI/CD processes, streamline project configuration, and improve error handling.
Added a new GitHub Actions workflow (`.github/workflows/swift.yml`) that includes jobs for building and testing on macOS, running `xcodebuild` tests, and enforcing SwiftLint for code quality.
* Removed the `SYMROOT` setting from both the Debug and Release build configurations in `azooKeyMac.xcodeproj/project.pbxproj`, allowing Xcode to use its default build directory. [[1]](diffhunk://#diff-e74651d5be8fe0e64f4081b0a15095d033917265749205b74902cda6ff36012bL423) [[2]](diffhunk://#diff-e74651d5be8fe0e64f4081b0a15095d033917265749 …
=> feat: add ci for testing `Core` and check the build-ability

Core/Sources/Core/InputUtils/Actions/UserAction.swift, Core/Sources/Core/InputUtils/InputState.swift, azooKeyMac/Configs/BoolConfigItem.swift, azooKeyMac/InputController/UserAction+getUserAction.swift, azooKeyMac/Windows/ConfigWindow.swift
Google日本語入力では以下のような設定があり、設定値を「半角」にすると、日本語入力モードにおいてスペースを入力した際でも「半角スペース」が入力されるようになります。ちなみにShift+Spaceだと全角スペースになります。
この設定と同等の内容になるような設定項目を追加しました。
個人的に、全角スペースを入力することがあまりないのでこの設定を有効にしていることと、Discordを覗いてみたら要望があったのであるといいのかなと思って追加させてもらいました。
InputState.swiftではConfigが読めるようになってなさそうだったので、UserActionで切り替えできるようにしました。
今回、`space`を`space(Bool)`にしています。最初、`fullSpace`というのを増やそうと思ったんですが、InputState.swiftの分岐の中で`space`が何度か登場しているので、`space(Bool)`のほうがシンプルにできそうと判断してこのようにしました。初見だと「`space(Bool)`のBoolってなんじゃ？」ってなりそうなのが微妙なところですが。
=> feat: 「スペースは常に半角を入力」をオンにすると、半角スペースを優先するようにしました

azooKeyMac/InputController/SegmentsManager.swift
タイピングゲームをやるときに全角数字に変換できなくて困るので、全角数字をまとめて変換できるようにした。
https://sanarome-typing.com/kanji-henkan-typing/
=> feat: 全角数字をまとめて変換できるように

azooKeyMac/InputController/azooKeyMacInputControllerHelper.swift
- 現在の状態を示す「ZenzaiをOFF」「ZenzaiをON」のテキストを、チェックマーク（✓ = 有効、チェックなし = 無効）による明確な状態表示に変更
- 設定項目とその他のメニューオプションの間に視覚的な区切り線を追加してグループ化を改善
- ユーザーが現在どの機能が有効になっているかを一目で確認できるようにしました
=> Improve menu bar UI clarity for Zenzai and Live Conversion settings

azooKeyMac/AppDelegate.swift
設定画面でペーストショートカットが効かない問題を修正できたので、共有させていただきます。
具体的には、非表示のメニューバーに Edit > Paste メニュー項目を追加し、First Responder チェーンに paste: アクションが正しく流れるようにしました。また、変換プロフィールや OpenAI Model name の欄ではコピーやカットのショートカットも便利かと思い、ペースト以外の標準的な Edit メニュー項目も追加しています。
関連 Issue: #102
=> fix: 設定画面でペーストコマンドが効かない

Core/Package.swift, Core/Sources/Core/InputUtils/Actions/ClientAction.swift, Core/Sources/Core/InputUtils/Actions/UserAction.swift, Core/Sources/Core/InputUtils/InputState.swift, azooKeyMac/InputController/SegmentsManager.swift, azooKeyMac/InputController/UserAction+getUserAction.swift, azooKeyMac/InputController/azooKeyMacInputController.swift
iOS版でも導入済みの「この候補の学習をリセット」の機能をひっそり導入する。
* 変換候補を選択する際、選択した状態で`^⌫`で利用できる。これはGoogle日本語入力の初期設定と同様のコマンド。
* ただし、現状特に視覚的なフィードバックなどは付けていないので、見て分かるものではない。
* 視覚的なフィードバックは後回しで、一応サポート、という感じでやっていきたい
=> feat: 「この候補の学習をリセット」機能を導入

azooKeyMac/AppDelegate.swift, azooKeyMac/Configs/StringConfigItem.swift, azooKeyMac/Extensions/KeychainHelper.swift
- KeychainHelperのメソッドをasync/awaitで非同期化
- OpenAiApiKeyにキャッシュ機能を追加し、Keychainアクセスを最小化
- アプリ起動時にKeychainから値を非同期で読み込む処理を追加
これにより、UIスレッドのブロックを防ぎ、アプリケーションの応答性が向上
=> refactor: Keychainの実装を非同期化してパフォーマンスを改善

azooKeyMac/InputController/CandidateWindow/BaseCandidateViewController.swift
ダークモードだと顕著な違いは見えにくいが、ライトモードでは比較的馴染んで見える
=> feat: 変換候補ウィンドウの背景を真っ白ではなくMaterialを用いたデザインに変更

azooKeyMac/InputController/CandidateWindow/BaseCandidateViewController.swift
followup: #150 
* マテリアルをより明るいもの（標準IMEに近いもの）に変更
* 文字サイズを16→18に拡大
* 文字色を30%のグレーに変更（標準IMEと揃えた）
* 縦方向の余白を広げた（やや見栄えが良くなる）
=> feat: 背景のマテリアルをより明るいものに変更し、文字サイズを大きくし、縦方向の余白を少し広げた

azooKeyMac/InputController/azooKeyMacInputController.swift
英数キーを用いて macOS 標準の入力ソースへ切り替える時に、azooKey で入力中の未確定テキスト(Marked Text)が失われる問題を修正しました。
以下の入力ソースの組み合わせにおいて、当不具合が発生していました。
- com.apple.keylayout.ABC
- dev.ensan.inputmethod.azooKeyMac.Japanese
日本語入力中に英数キーが押下されると、 azooKey のキーイベント処理よりも早く deactivateServer メソッドが呼び出されます。この deactivateServer 内で強制的に空文字列を挿入していたため、ユーザーが入力中の未確定テキストが消去されてしまう事象が発生していました。
deactivateServer メソッドが呼び出された際に、segmentsManager に未確定テキストが存在する場合、そのテキストを確定するように変更しました。
入力フィールドがないアプリへの切り替えなどでdeactivateServerが呼び出された時に、未確定状態が意図せず残らないように、入力状態をリセットしてIM内部をクリーンに保ちます。
関連 Issue: #138
=> fix: 変換確定に英数キーを使用すると入力が消える

ConverterServer/ConverterServer.entitlements, ConverterServer/ConverterXPC.swift, ConverterServer/main.swift, ConverterXPC/ConverterXPC.entitlements, ConverterXPC/ConverterXPC.swift, ConverterXPC/ConverterXPCProtocol.swift, ConverterXPC/Info.plist, ConverterXPC/main.swift, azooKeyMac.xcodeproj/project.pbxproj, azooKeyMac/InputController/azooKeyMacInputController.swift, azooKeyMac/InputController/azooKeyMacInputControllerHelper.swift, azooKeyMac/azooKeyMac.entitlements
このPRでは、プロセス分離に向けたサンプルを実装した。メニューバー上で「プロセスと通信」を押すと、`ConverterServer`という起動している別プロセスにCross-Process Connectionが飛び、簡単なデータの送受信が実行され、結果がデバッグログに表示される。
* `ConverterServer`: Launch Agentとして変換を担うプロセスを想定。
* `ConverterXPC`: On-Demandで起動され、1つの処理を終えると終了するプロセス。今回の実装で試したが、不要であった。
`~/Library/LaunchAgents`に`dev.ensan.inputmethod.azooKeyMac.ConverterServer.plist`を配置して使える。
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>Label</key>
<string>dev.ensan.inputmethod.azooKeyMac.ConverterServer</string>
<key>ProgramArguments</key>
<array>
<string>/Library/Input Methods/azooKeyMac.app/Contents/MacOS/ConverterServer</string>
</array>
<key>MachServices</key>
<dict> …
```
=> [DNM] feat: minimum implementation of XPC service

azooKeyMac/InputController/UserAction+getUserAction.swift
Control+M キーで変換を確定できるようにしました。
すでに Control+P/N などの emacs/vim 風のキーバインディングがサポートされているため、合わせて Control+M もサポートするようにしました。
mac標準やGoogle日本語入力などでも Ctrl+M は変換の確定に割り当てられているため、一般的なキーバインディングに合わせる目的もあります。
以下の状態で Control+M を押した際に、Enter キーと同じ動作をすることを確認しました。
- 文字入力中（composing状態）
- 変換候補プレビュー中（previewing状態）
- 候補選択中（selecting状態）
=> feat: Control+M で変換を確定できるように

Core/Package.swift, azooKeyMac/Configs/StringConfigItem.swift, azooKeyMac/InputController/SegmentsManager.swift, azooKeyMac/InputController/azooKeyMacInputController.swift
このPRではAzooKeyKanaKanjiConverterのバージョンをv0.9系（beta）に更新する。機能的な変更としては以下のような変更が取り込まれる。特に https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/223 により、長く問題となっていた`ComposingText`の`input`が破壊される問題が解消され、将来的には英字変換などの導入が可能になる。
* 起動時の処理の安定化 by @mtgto in https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/217
* Lattice処理を二重インデックス化し、ComposingTextレベルで扱っていたアドホックな処理を削除 by @ensan-hcl https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/223
なお、このほかにv0.9.0ではいくつかのAPIの破壊的変更が生じるため、本PRではこれにも対処している。具体的には`Candidate.correspondingCount`が型違いの`Candidate.composingCount`に変更になった。
=> feat: AzooKeyKanaKanjiConverterをv0.9.0に更新し、破壊的変更に対処

azooKeyMac/InputController/SegmentsManager.swift
`ComposingCount`は`.composite`のケースがあるため、単純な直接比較をすべきでない。`Equatable`を削除にしたほうがいいかも
=> fix: ComposingCount同士を比較することで発生するエラーに対処

Core/Package.swift, azooKeyMac/Configs/CustomCodableConfigItem.swift, azooKeyMac/InputController/SegmentsManager.swift, azooKeyMac/InputController/azooKeyMacInputController.swift, azooKeyMac/Windows/ConfigWindow.swift
AzooKeyKanaKanjiConverterでローマ字かな入力周りに抜本的な変更を導入し、カスタムテーブルのサポートに成功した。これに伴って、以下の2つの変更を取り込んだ。
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/227
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/228
これにより、カスタムローマ字テーブルのサポート（ #117 ）、かな入力のサポート（ #114 ）、末尾`n->ん`変換（ #178 ）などに対処することができる。このPRでは、
1. カスタムローマ字テーブル機能のサブセットとして、AZIK入力に対応
2. 末尾`n->ん`変換に対応 ( resolve #178 )
の2つが追加される。
なお、この変更は非常に大規模であり、意図しない不具合が混入する可能性があるので、怪しい挙動を見つけた場合は報告されたい。
=> feat: AzooKeyKanaKanjiConverterを更新し、AZIKに対応し、末尾の`n`を`ん`に変更する機能をサポート

Core/Package.swift, azooKeyMac/AppDelegate.swift, azooKeyMac/InputController/SegmentsManager.swift
このPRではAzooKeyKanaKanjiConverterの変更を取り入れ、破壊的変更に対処しています。
重要なものとしては**パフォーマンスの改善**が含まれます。以下の一連のPRで、Zenzai利用時の変換速度が大幅に改善しており、特に長文の入力時には実感を伴う性能向上になっています。
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/245
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/246
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/247
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/248
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/249
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/250
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/252
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/253
そのほかの変更詳細は以下で確認できます。
* https://github.com/azooKey/AzooKeyKanaKanjiConverter/compare/v0.10.1...ee14c15ae9970c74a7a958aece64593ff1988141
=> feat: AzooKeyKanaKanjiConverterの変更を取り入れ、破壊的変更に対処 / Zenzaiのパフォーマンスを大幅に改善

Core/Sources/Core/MagicConversion/OpenAIClient.swift, azooKeyMac/InputController/azooKeyMacInputController+SelectedTextTransform.swift, azooKeyMac/Windows/ConfigWindow.swift
#170 で言及した2ステップの1つ目。`Core/`に`OpenAIClient`の実装を移動し、再利用性を高める。
=> refactor: OpenAIClientの実装をCore/側に移動

Core/Sources/Core/InputUtils/InputState.swift
デッドキー入力後に数字キーを入力したときの振る舞いを修正しました。
従来は `¨` のみが入力されていましたが、この修正で `¨1` と入力されるようになります。
=> fix: デッドキー+数字キーの振る舞い
